"use client";

import Card from "../ui/Card";
import SectionTitle from "../ui/SectionTitle";

import PreviewTable from "../preview/PreviewTable";
import CRMTable from "../results/CRMTable";

import EmptyState from "../ui/EmptyState";
import LoadingSkeleton from "../ui/LoadingSkeleton";

import { FileSpreadsheet } from "lucide-react";

export default function PreviewSection({
  parsedData,
  headers,
  isParsing,
  crmRecords,
}) {
  // ============================
  // Loading
  // ============================

  if (isParsing) {
    return (
      <Card>

        <SectionTitle
          title="CSV Preview"
          subtitle="Parsing your CSV..."
        />

        <div className="space-y-4">

          <LoadingSkeleton className="h-12 w-full" />

          <LoadingSkeleton className="h-80 w-full" />

        </div>

      </Card>
    );
  }

  // ============================
  // Empty
  // ============================

  if (!parsedData.length) {
    return (
      <Card>

        <SectionTitle
          title="CSV Preview"
          subtitle="Preview your uploaded CSV before importing."
        />

        <EmptyState
          icon={<FileSpreadsheet size={48} />}
          title="No CSV Uploaded"
          description="Upload a CSV file to preview its contents before AI processing."
        />

      </Card>
    );
  }

  // ============================
  // Preview
  // ============================

  return (
    <div className="space-y-8">

      {/* Preview Card */}

      <Card>

        <SectionTitle
          title="CSV Preview"
          subtitle="Preview your uploaded CSV before importing."
        />

        <div className="mb-6 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">

          <p className="font-semibold text-green-600">
            CSV Parsed Successfully ✅
          </p>

          <p className="text-sm text-slate-500">
            {parsedData.length} Rows • {headers.length} Columns
          </p>

        </div>

        <PreviewTable
          headers={headers}
          parsedData={parsedData}
        />

      </Card>

      {/* CRM Preview */}

      {crmRecords.length > 0 && (

        <Card>

          <SectionTitle
            title="AI CRM Preview"
            subtitle="Records generated by AI."
          />

          <CRMTable
            records={crmRecords}
          />

        </Card>

      )}

    </div>
  );
}